// ─── Claude 界面全面汉化脚本 ───
// 可复制给任何人使用，自动检测 Claude 目录并生成汉化文件
// 用法: node translate.js <Claude资源目录> [输出目录]
// 输出目录省略时写入到临时目录

const fs = require('fs');
const path = require('path');

const claudeDir = process.argv[2];
if (!claudeDir || !fs.existsSync(path.join(claudeDir, 'en-US.json'))) {
  console.error('❌ 用法: node translate.js <Claude资源目录>');
  console.error('例如: node translate.js "C:\\Program Files\\WindowsApps\\Claude_1.x\\app\\resources"');
  process.exit(1);
}

const outDir = process.argv[3] || path.join(require('os').tmpdir(), 'claude_zh_' + Date.now());
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

// ─── 翻译表 ───
const T = {
  // 主文件
  'Actual Size': '实际大小', 'Copy': '复制', 'Edit': '编辑', 'Team': '团队',
  'Forget': '忘记', 'Leave': '离开', 'Cancel': '取消', 'Close': '关闭', 'Close Window': '关闭窗口',
  'Save': '保存', 'Delete': '删除', 'Undo': '撤销', 'Redo': '重做', 'Cut': '剪切', 'Paste': '粘贴',
  'Developer': '开发者', 'Debug': '调试', 'Open': '打开', 'Window': '窗口', 'Not now': '稍后', 'Later': '稍后',
  'Troubleshooting': '故障排除', 'About...': '关于…', 'Settings...': '设置…', 'Settings…': '设置…',
  'Reload': '重新加载', 'Refresh': '刷新', 'Install': '安装', 'Uninstall': '卸载', 'Reinstall': '重新安装',
  'Exit': '退出', 'Quit': '退出', 'Quit anyway': '仍然退出', 'Preview': '预览', 'preview': '预览',
  'Select All': '全选', 'Clean Up': '清理', 'Search': '搜索', 'Filter': '筛选', 'Restart': '重启',
  'Restart Now': '立即重启', 'Restart Required': '需要重启', 'Reset': '重置', 'Forward': '前进', 'Back': '返回',
  'View': '查看', 'Name': '名称', 'Level': '等级', 'Heap': '堆', 'Choose': '选择', 'Enable': '启用',
  'Disable': '禁用', 'OK': '确定', 'Yes': '是', 'No': '否', 'Help': '帮助', 'Connected': '已连接',
  'Disconnected': '已断开', 'Error': '错误', 'Warning': '警告', 'Success': '成功', 'Find': '查找',
  'Code': '代码', 'Design': '设计', 'File': '文件', 'System': '系统', 'Uptime': '运行时间',
  'Battery': '电池', 'Charging': '充电中', 'Velocity': '速度', 'Progress': '进度', 'Availability': '可用性',
  'Free': '免费', 'Pro': '专业版', 'Enterprise': '企业版', 'Max': '最大', 'Unlimited': '无限',
  'New Conversation': '新对话', 'Copy link': '复制链接', 'Copy URL': '复制网址', 'Copy Image': '复制图片',
  'Copy Link Address': '复制链接地址', 'Copy Image Address': '复制图片地址', 'Paste': '粘贴', 'Look Up': '查询',
  'Learn more': '了解更多', 'Get Support': '获取支持', 'Get support': '获取支持', 'Help': '帮助',
  'Submit Feedback': '提交反馈', 'About Claude': '关于 Claude', 'Clear Cache and Restart': '清除缓存并重启',
  'Reset Application Data': '重置应用数据', 'Change…': '更改…', 'Pair': '配对', 'Connect': '连接',
  'Open Settings': '打开设置', 'Open Documentation': '打开文档', 'Open Chrome Web Store': '打开 Chrome 网上应用店',
  'Reload This Page': '重新加载此页面', 'Reload': '重新加载', 'Dismiss': '关闭', 'Sign in again': '重新登录',
  'Computer use': '计算机控制', 'Web search': '网络搜索', 'Analysis tool': '分析工具', 'Inspect tool': '检查工具',
  'Artifacts': '内容', 'Home': '首页', 'Chat': '聊天', 'Projects': '项目', 'Project': '项目',
  'Messages': '消息', 'Message': '消息', 'Sessions': '会话', 'Session': '会话', 'History': '历史',
  'Activity': '活动', 'Notifications': '通知', 'Notification': '通知', 'Inbox': '收件箱',
  'Favorites': '收藏夹', 'Recent': '最近', 'Archived': '已归档', 'Downloads': '下载', 'Uploads': '上传',
  'Account': '账户', 'Profile': '个人资料', 'Privacy': '隐私', 'Security': '安全', 'Compliance': '合规',
  'Admin': '管理员', 'Administrator': '管理员', 'Owner': '所有者', 'User': '用户', 'Users': '用户',
  'Extensions': '扩展', 'Extension': '扩展', 'Plugins': '插件', 'Integrations': '集成', 'Connectors': '连接器',
  'Connector': '连接器', 'Documentation': '文档', 'Changelog': '更新日志', 'Settings': '设置',
  'General': '通用', 'Appearance': '外观', 'Theme': '主题', 'Light': '浅色', 'Dark': '深色',
  'Language': '语言', 'Region': '地区', 'Preferences': '偏好设置', 'Font size': '字体大小',
  'Hotkeys': '快捷键', 'Keyboard shortcuts': '键盘快捷键', 'Accessibility': '辅助功能',
  'Zoom': '缩放', 'Zoom In': '放大', 'Zoom Out': '缩小', 'Full Screen': '全屏', 'Enter Full Screen': '进入全屏',
  'Exit Full Screen': '退出全屏', 'Minimize': '最小化', 'Maximize': '最大化', 'Restore': '恢复',
  'Show': '显示', 'Hide': '隐藏', 'Show All': '显示全部',
  'Show in Explorer': '在资源管理器中显示', 'Show in Finder': '在 Finder 中显示', 'Reveal in Finder': '在 Finder 中显示',
  'Open in Browser': '在浏览器中打开', 'Open Link in Browser': '在浏览器中打开链接',
  'Show Dev Tools': '显示开发者工具', 'Show All Dev Tools': '显示所有开发者工具', 'Inspect Element': '检查元素',
  'Developer mode': '开发者模式', 'Enable Developer Mode': '启用开发者模式', 'Enable Developer Mode?': '启用开发者模式？',
  'Copy Installation ID': '复制安装 ID', 'Generate Diagnostic Report': '生成诊断报告',
  'Record Net Log (30s)': '录制网络日志（30 秒）', 'View Process Logs': '查看进程日志',
  'Open MCP Log File': '打开 MCP 日志文件', 'Open MCP Log File...': '打开 MCP 日志文件…',
  'Reload MCP Configuration': '重新加载 MCP 配置', 'MCP Configuration Reload Failed': 'MCP 配置重载失败',
  'Load Remote Claude.ai': '加载远程 Claude.ai', 'Load Local Claude.ai': '加载本地 Claude.ai',
  'Load Staging Claude.ai': '加载 Staging Claude.ai', 'Fix ownership': '修复所有权',
  'Ownership fix failed': '所有权修复失败', 'Fix required for auto-updates': '需要修复才能自动更新',
  'Disk cleanup is currently disabled.': '磁盘清理当前已禁用。', 'Cowork Disk Cleanup': 'Cowork 磁盘清理',
  'Free Up Cowork Disk Space…': '释放 Cowork 磁盘空间…',
  'Delete VM Sessions and Restart': '删除虚拟机会话并重启',
  'Delete VM Bundle and Restart': '删除虚拟机包并重启',
  'Delete Cowork VM Bundle and Restart…': '删除 Cowork 虚拟机包并重启…',
  'Delete Cowork VM Sessions and Restart…': '删除 Cowork 虚拟机会话并重启…',
  'Enable Cowork VM Debug Logging': '启用 Cowork 虚拟机调试日志',
  'Enable Cowork SDK Debugging': '启用 Cowork SDK 调试',
  'Reset Application Data': '重置应用数据', 'Something went wrong': '出了点问题', 'Please try again': '请重试',
  'Network error': '网络错误', 'Connection lost': '连接断开', 'Reconnecting...': '重新连接中…',
  'Offline': '离线', 'Online': '在线', 'No results': '无结果', 'No data': '无数据',
  'No messages yet': '暂无消息', 'No conversations yet': '暂无对话',
  'Created': '创建时间', 'Modified': '修改时间', 'Last modified': '最近修改', 'Last opened': '最近打开',
  'Size': '大小', 'Type': '类型', 'Date': '日期', 'Status': '状态', 'Priority': '优先级',
  'Action': '操作', 'Actions': '操作', 'More options': '更多选项', 'All': '全部', 'None': '无', 'Any': '任意',
  'Other': '其他', 'More': '更多', 'Less': '更少', 'New': '新建', 'Old': '旧版',
  'Today': '今天', 'Yesterday': '昨天', 'This week': '本周', 'This month': '本月', 'Earlier': '更早',
  'Custom': '自定义', 'Manual': '手动', 'Automatic': '自动', 'Public': '公开', 'Private': '私有',
  'Internal': '内部', 'External': '外部', 'Active': '活跃', 'Inactive': '不活跃',
  'Enabled': '已启用', 'Disabled': '已禁用', 'Visible': '可见', 'Hidden': '隐藏',
  'Read': '读取', 'Write': '写入', 'Read-only': '只读', 'Read and write': '读写', 'Full access': '完全访问',
  'Grant': '授予', 'Revoke': '撤销', 'Request': '请求', 'Accept': '接受', 'Reject': '拒绝', 'Decline': '拒绝',
  'Approved': '已批准', 'Pending': '待处理', 'Expired': '已过期', 'Completed': '已完成',
  'Failed': '失败', 'Failed to load': '加载失败', 'Could not load': '无法加载',
  'Access denied': '访问被拒绝', 'Not found': '未找到', 'Not available': '不可用',
  'Unsupported': '不支持', 'Invalid': '无效', 'Required': '必填', 'Optional': '可选', 'Empty': '空',
  'Untitled': '无标题', 'Unnamed': '未命名',
  'What can I help you with?': '有什么可以帮您的？', 'What can I help you with today?': '今天有什么可以帮您的？',
  'Attach files': '附加文件', 'Attach': '附加', 'Upload file': '上传文件', 'Download file': '下载文件',
  'Open file': '打开文件', 'Save file': '保存文件', 'Save as': '另存为', 'File name': '文件名',
  'File size': '文件大小', 'File type': '文件类型', 'Select file': '选择文件', 'Select files': '选择文件',
  'Choose file': '选择文件', 'Choose folder': '选择文件夹', 'Choose Data Folder': '选择数据文件夹',
  'Select folder': '选择文件夹', 'Browse': '浏览', 'Path': '路径', 'Location': '位置',
  'Open folder': '打开文件夹', 'Open File…': '打开文件…',
  'Load more': '加载更多', 'Show more': '显示更多', 'Show less': '显示更少', 'See all': '查看全部',
  'Install Extension': '安装扩展', 'Install Extension...': '安装扩展…', 'Install Unpacked Extension...': '安装未打包扩展…',
  'Select Extension Folder': '选择扩展文件夹', 'Open Extensions Folder...': '打开扩展文件夹…',
  'Open App Config File...': '打开应用配置文件…', 'Open Developer Config File...': '打开开发者配置文件…',
  'Extensions Disabled': '扩展已禁用', 'Extension Installation Failed': '扩展安装失败', 'Extension Preview Failed': '扩展预览失败',
  'Failed to install extension': '扩展安装失败', 'Failed to preview extension': '扩展预览失败',
  'Failed to preview extension.': '扩展预览失败。', 'Extension preview failed': '扩展预览失败', 'Extension installation failed': '扩展安装失败',
  'Hardware Buddy & Maker Devices': '硬件伴侣与外部设备', 'Choose your Buddy': '选择您的外部设备',
  'No buddy paired': '未配对外部设备', 'Pair with {name}': '与 {name} 配对', 'Tap to pair:': '点击配对：',
  'Pairing code': '配对码', 'Send to Device': '发送到设备', 'Device did not respond': '设备无响应',
  'None found. Make sure yours is on and nearby.': '未找到设备，请确保设备已开启且在附近。',
  'Build your own device': '构建您自己的设备', 'Open Hardware Buddy…': '打开硬件伴侣…',
  'Reference implementation': '参考实现',
  'Plan usage': '套餐用量', 'Plan usage · {tier}': '套餐用量 · {tier}',
  'Usage credits': '使用额度', 'Usage credits · {used}': '使用额度 · {used}',
  'Usage credits · {used} of {limit}': '使用额度 · {used} / {limit}',
  'Extra usage · {used}': '额外用量 · {used}', 'Extra usage · {used} of {limit}': '额外用量 · {used} / {limit}',
  'Weekly · all models': '每周 · 全部模型', 'Weekly · {product}': '每周 · {product}',
  '{tier} plan': '{tier} 套餐', '{product} grant': '{product} 授权', '5-hour limit': '5 小时限制',
  'Billing': '账单', 'Add payment method': '添加支付方式', 'Invoice': '发票', 'Receipt': '收据',
  'Tax': '税费', 'Subtotal': '小计', 'Total': '合计', 'Due': '应付', 'Paid': '已支付', 'Pending': '待处理',
  'Unknown error': '未知错误', 'Error clearing cache': '清除缓存出错', 'Error accessing logs': '访问日志出错',
  'Error Opening Folder': '打开文件夹出错', 'Folder not allowed': '文件夹不被允许', 'Folder access disabled': '文件夹访问已禁用',
  'Some folders were skipped': '部分文件夹已被跳过', 'Connection is unencrypted': '连接未加密',
  'Check your network connection': '请检查网络连接', 'No space was freed.': '未释放任何空间。',
  'Skill file error': '技能文件错误', 'Skill file not found': '未找到技能文件', 'Skill file too large': '技能文件过大',
  'Cannot open skill': '无法打开技能', 'Failed to open skill file.': '无法打开技能文件。', 'Prototypes': '原型',
  'Set up computer use': '设置计算机控制', 'Disable Hardware Acceleration': '禁用硬件加速',
  'Find in page': '在页面中查找', 'Find Next': '查找下一个', 'Find Previous': '查找上一个',
  'Previous match': '上一个匹配项', 'Next match': '下一个匹配项', 'Close find bar': '关闭查找栏',
  'Caps Lock': '大写锁定', 'App Features': '应用功能', 'Update Available': '更新可用',
  'No Update Available': '无可用更新', 'You are running the latest version.': '您正在运行最新版本。',
  'Included until June 22': '包含至 6 月 22 日', 'Org default': '组织默认',
  'Complex, detailed work': '复杂、深度的工作', 'Light, casual tasks': '轻量、日常任务',
  'For your toughest challenges': '应对最困难的任务', 'Respond right away': '立即响应',
  'Match thinking to complexity': '根据复杂度匹配思考深度', 'Think longer for complex tasks': '复杂任务思考更久',
  'Quick replies to simple questions': '简单问题快速回复', 'Can think for more complex tasks': '可为更复杂的任务思考',
  'Thinks for more complex tasks': '为更复杂的任务思考', 'Always uses deep reasoning': '始终使用深度推理',
  'Balanced for everyday work': '日常工作平衡模式', 'Most capable for ambitious work': '最具创造力的模型',
  'Most efficient for everyday tasks': '日常任务最高效', 'Best for math and coding challenges': '数学与编码最佳',
  'Best for most use cases': '适合大多数场景', 'Fastest for quick answers': '快速回答最快捷',
  'Opus consumes usage limits faster than other models': 'Opus 消耗额度更快', 'Uses usage credits': '消耗额度',
  'Extra': '额外', 'Extended': '扩展', 'Thinking': '思考', 'Extended thinking': '扩展思考',
  'Adaptive': '自适应', 'Adaptive thinking': '自适应思考', 'Auto thinking': '自动思考',
  'Default': '默认', 'Off': '关闭', 'Instant': '即时', 'High': '高', 'Medium': '中', 'Low': '低', 'Max': '最大',
  'Apply Changes': '应用更改',
  'Apply': '应用',
  'Changes': '更改',
  'Apply Changes': '应用更改',
  'Connectors & extensions': '连接器与扩展',
  'Egress Requirements': '出站要求',
  'Egress': '出站',
  'Requirements': '要求',
  'Connector tools': '连接器工具',
  'Top Connectors': '常用连接器',
  'This connector has no tools to configure.': '此连接器无可配置的工具。',
  'This connector\'s server is currently unavailable. Try again in a moment.': '此连接器服务器当前不可用，请稍后重试。',
  'Couldn\'t load connector details. Please try again.': '无法加载连接器详情，请重试。',
  'Couldn\'t load connectors.': '无法加载连接器。',
  'No connectors match your search': '没有匹配的连接器',
  'No connectors match your filters.': '没有匹配筛选条件的连接器。',
  'Contact an organization owner to install connectors': '联系组织所有者安装连接器',
  '{connectorName} connector': '{connectorName} 连接器',
  '{count, plural, one {# connector needs additional configuration. Enable it from the Connectors page.} other {# connectors need additional configuration. Enable them from the Connectors page.}}': '有 {count} 个连接器需要额外配置，请从连接器页面启用。',
  'Endpoint': '端点',
  'Rate Limit': '速率限制',
  'Rate limit': '速率限制',
  'Timeout': '超时',
  'Retry': '重试',
  'Retrying': '重试中',
  'Retrying in {seconds}s...': '将在 {seconds} 秒后重试…',
  'Authorization': '授权',
  'Authorization URL': '授权地址',
  'Authentication': '认证',
  'Base URL': '基础地址',
  'Headers': '请求头',
  'Credentials': '凭据',
  'OAuth': 'OAuth 认证',
  'OAuth 2.0 client credentials': 'OAuth 2.0 客户端凭据',
  'OAuth 2.0 JWT bearer': 'OAuth 2.0 JWT 载体',
  'Client ID': '客户端 ID',
  'Client Secret': '客户端密钥',
  'Client secret': '客户端密钥',
  'Token URL': '令牌地址',
  'Auth URL': '认证地址',
  'Scope': '范围',
  'Redirect URI': '重定向地址',
  'Grant type': '授权类型',
  'Refresh': '刷新',
  'Refresh tools list': '刷新工具列表',
  'Expiry': '过期',
  'Provider': '提供方',
  'Configure': '配置',
  'Configured': '已配置',
  'Active': '活跃',
  'Inactive': '不活跃',
  'Status': '状态',
  'Health': '健康',
  'Healthy': '健康',
  'Unhealthy': '不健康',
  'Proxy': '代理',
  'Allowlist': '允许列表',
  'Domain allowlist': '域名允许列表',
  'Blocklist': '阻止列表',
  'Firewall': '防火墙',
  'Certificate': '证书',
  'Verify': '验证',
  'Verifying': '验证中',
  'TLS': 'TLS',
  'mTLS': 'mTLS',
  'Self-signed': '自签名',
  'Verify in Settings': '在设置中验证',
  'Identity verification is required to continue. <link>Verify in Settings</link>.': '需要身份验证才能继续。<link>在设置中验证</link>。',
  'Connected to {name}': '已连接到 {name}',
  'Connected files': '已连接的文件',
  'No active tasks.': '无活跃任务。',
  'Active tasks': '活跃任务',
  'Interactive tools': '交互工具',
  'Interactive artifact': '交互式内容',
  'Discard changes': '放弃更改',
  'Discard uncommitted changes?': '放弃未提交的更改？',
  'Changes saved.': '更改已保存。',
  'Review changes': '审查更改',
  'Stash changes': '暂存更改',
  'All connectors are on': '所有连接器已开启',
  'Desktop-app OAuth client ID': '桌面应用 OAuth 客户端 ID',
  'GCP credentials file path': 'GCP 凭据文件路径',
  '{provider} credentials': '{provider} 凭据',
  '{provider} key details': '{provider} 密钥详情',
  'Remove from allowlist': '从允许列表中移除',
  'Disable extension allowlist': '禁用扩展允许列表',
  'IP allowlist updated.': 'IP 允许列表已更新。',
  'https://REGION-aiplatform-ENDPOINT_ID.p.googleapis.com': 'https://地域-aiplatform-端点ID.p.googleapis.com',
  'Headers helper script': '请求头辅助脚本',
  'Enter the details of the key you\'ve configured in your {provider} account.': '输入您在 {provider} 账户中配置的密钥详情。',
  'Includes a value set by provider: {provider}': '包含由提供方设置的值：{provider}',
  'Use this information to configure Claude in your identity provider': '使用此信息在您的身份提供者中配置 Claude',
  'Advanced SCIM provisioning is enabled. Seat types and roles are managed through your identity provider.': '高级 SCIM 配置已启用，席位类型和角色通过身份提供者管理。',
  'Your connection works, but the provider rejected a test request. Often a model-access or quota issue.': '连接正常，但提供方拒绝了测试请求，通常是模型访问或配额问题。',
  'You\'re running Claude through your organization\'s own inference provider ({providerDisplayName}). Your conversations are sent there, not to Anthropic, and are governed by your organization\'s agreement with that provider.': '您正在通过组织的自建推理提供方（{providerDisplayName}）运行 Claude，对话将发送到那里而非 Anthropic。',
  'The provider didn\'t return a refresh token. You may need to revoke previous consent at the provider and try again.': '提供方未返回刷新令牌，您可能需要撤销之前的授权后重试。',
  'PSC endpoint, if using one.': 'PSC 端点（如使用）。',
  'OpenTelemetry collector endpoint': 'OpenTelemetry 采集器端点',
  'Rate limit override cleared for 30 days': '速率限制覆盖已清除（30 天）',
  'GitHub rate limit exceeded. Wait a few minutes and try again.': 'GitHub 速率限制已达，请等待几分钟后重试。',
  'Credential helper timeout': '凭据辅助程序超时',
  'The OAuth provider rejected the authorization. Try again.': 'OAuth 提供方拒绝了授权，请重试。',
  'Couldn\'t confirm the authorization result. Refresh the credentials list; if the new credential doesn\'t appear, try again.': '无法确认授权结果，请刷新凭据列表；如新凭据未出现请重试。',
  'Waiting for authorization…': '等待授权…',
  'There was an error completing authentication. Please confirm that you have permission to access the service, that you\'re using the correct credentials, and that your server handles auth correctly.': '完成认证时出错，请确认您有权访问该服务、使用正确的凭据且服务器正确处理了认证。',
  'Require re-authentication for password change': '密码更改时要求重新认证',
  'To use Claude within Canvas, we need your permission to access your authentication.': '要在 Canvas 中使用 Claude，我们需要您的许可来访问认证信息。',
  'Desktop-app OAuth client ID. Enables Sign in with Google instead of a credentials file.': '桌面应用 OAuth 客户端 ID，启用 Google 登录替代凭据文件。',
  'Vertex OAuth client ID': 'Vertex OAuth 客户端 ID',
  'Scope an engagement': '设定工作范围',
  'This key includes a scope that can permanently delete data across any organization under the same parent organization. Deletions cannot be undone.': '此密钥包含可永久删除同一父组织下任何组织数据的范围，删除不可撤销。',
  'Use localhost only if your IdP\'s registered redirect URI specifies it.': '仅在您的身份提供者注册的重定向 URI 指定时使用 localhost。',
  '{status} · {ref}': '{status} · {ref}',
  'HTTP {status}': 'HTTP {status}',
  'The service returned HTTP {status}. Couldn\'t verify the response — save and try a request if this looks right.': '服务返回 HTTP {status}，无法验证响应——如确认无误请保存并尝试请求。',
  'Check {statusLink} for updates.': '查看 {statusLink} 了解更新。',
  'GitHub is unreachable. Pull request status may be out of date.': 'GitHub 无法访问，PR 状态可能不是最新的。',
  'Check icon': '检查图标',
  'View CI checks on GitHub': '在 GitHub 上查看 CI 检查',
  'Could not check deployment terms. Please try again.': '无法检查部署条款，请重试。',
  'You may not have access to this repository on GitHub, or it may not be in the Claude GitHub App\'s selection for your organization. It can\'t be scanned. Click to recheck.': '您可能没有此仓库的访问权限，或它不在组织的 Claude GitHub 应用选择范围内，无法扫描。点击重新检查。',
  'Check that your SSH host or local proxy is reachable, then try again.': '请确认您的 SSH 主机或本地代理可达，然后重试。',
  'Microphone access wasn\'t granted. You can check your browser settings and try again.': '未授予麦克风访问权限，请检查浏览器设置后重试。',
  'Your account was authorized, but {serverName} returned an error when connecting. You can try again, or check that the server is working.': '您的账户已授权，但 {serverName} 在连接时返回错误，请重试或检查服务器是否正常运行。',
  'Your terminal\'s Claude Code session stopped responding. Check your terminal for errors, then resend your message.': '终端的 Claude Code 会话无响应，请检查终端错误后重新发送消息。',
  'That target is already routed to a different agent proxy. Dissociate it there first.': '该目标已路由到其他代理，请先解除关联。',
  'Error rates reflect traffic through Anthropic\'s HTTP proxy; servers reached only via legacy WebSocket won\'t show data here. A high rate on one Anthropic product may reflect a client-side issue on our end rather than your server.': '错误率反映通过 Anthropic HTTP 代理的流量，仅通过旧版 WebSocket 连接的服务器不会显示数据。',
  'No instances heartbeating yet. Deploy the proxy with the registration secret.': '尚无实例发送心跳，请使用注册密钥部署代理。',
  'Extension removed from global blocklist': '扩展已从全局阻止列表中移除',
  'Paste a PEM-encoded certificate (-----BEGIN CERTIFICATE-----).': '粘贴 PEM 编码的证书（-----BEGIN CERTIFICATE-----）。',
  'Analyzing your certificate. This can take up to 30 seconds.': '正在分析您的证书，最多可能需要 30 秒。',
  'The certificate couldn\'t be analyzed. Try again.': '无法分析证书，请重试。',
  'There was an error verifying your code. If the problem persists <link>contact support</link> for assistance.': '验证代码时出错，如问题持续存在<link>请联系支持</link>。',
  'The text encoding for <b>{fileName}</b> could not be determined. Choose an encoding and verify with the preview.': '无法确定 <b>{fileName}</b> 的文本编码，请选择编码并通过预览验证。',
  'Handle big, complex tasks by splitting up work, looping until done, and verifying the results.': '通过拆分工作、循环执行直至完成并验证结果来处理大型复杂任务。',
  'Verifying your payment…': '正在验证付款…',
  'Couldn\'t verify eligibility': '无法验证资格',
  'Couldn\'t load shared content. Refresh and try again.': '无法加载共享内容，刷新后重试。',
  'We couldn\'t verify your eligibility right now. Refresh the page to try again.': '目前无法验证您的资格，请刷新页面后重试。',
  'Couldn\'t load all spend limits. Refresh the page before editing so daily and weekly limits aren\'t missed.': '无法加载所有消费限额，请在编辑前刷新页面以免遗漏每日和每周限额。',
  'Failed to revoke invitation. Please refresh the page and try again.': '撤销邀请失败，请刷新页面后重试。',
  'This webhook is already verified. Close and refresh to see its current state.': '此 Webhook 已验证，关闭并刷新以查看当前状态。',
  'Couldn\'t load model settings. Refresh to change this role\'s default.': '无法加载模型设置，请刷新以更改此角色的默认值。',
  'Couldn\'t send your response. Refresh and try again.': '无法发送回复，刷新后重试。',
  'Couldn\'t load this limit. Refresh the page to try again.': '无法加载此限制，请刷新页面后重试。',
  'Your checkout session expired. Click Try again to start a new one.': '结账会话已过期，点击重试开始新的结账。',
  'Error sending code. Double check your phone number.': '发送验证码出错，请仔细检查您的手机号码。',
  'Failed to connect to SSH server. Check your connection and try again.': '无法连接到 SSH 服务器，请检查连接后重试。',
  'Your sign-in session has expired, so Dispatch is disconnected on this device. Sign in again to reconnect.': '登录会话已过期，Dispatch 在此设备上已断开，请重新登录。',
  'Can\'t reach {appName} right now — it may need to be reconnected.': '当前无法访问 {appName}——可能需要重新连接。',
  'Check in when you want or just let Claude cook.': '随时查看进展，或让 Claude 自行处理。',
  'Cowork can work on complex tasks across {connectorList} without you watching. Send it off, come back to results.': 'Cowork 可以在 {connectorList} 上处理复杂任务而无需您实时关注。派发任务后回来查看结果即可。',
  'I\'ll pull context from your files and connectors': '我将从您的文件和连接器中获取上下文',
  'I have run every tool via MCP Inspector or as a custom connector in Claude': '我已通过 MCP Inspector 或自定义连接器运行了每个工具',
  '{names} need additional consent. Finish setting them up in connector settings.': '{names} 需要额外授权，请在连接器设置中完成配置。',
  '{n, plural, one {# connector needs} other {# connectors need}} reconnecting — they belong to the original owner and weren\'t copied. Add your own from the connector picker.': '有 {n} 个连接器需要重新连接——它们属于原始所有者且未被复制，请从连接器选择器中添加您自己的。',
  '<bold>Act without asking is on.</bold> Claude works, uses connectors, browses the web, and controls apps on your computer without pausing for approval. You can turn off individual connectors in the Add menu. <link>See safe use tips</link>': '<bold>免询问模式已开启。</bold>Claude 可直接工作、使用连接器、浏览网页和控制应用而无需暂停等待批准。您可以在添加菜单中关闭单个连接器。<link>查看安全使用提示</link>',
  'Model, connectors, and plugins for this Conway. Account-wide settings stay in your Claude settings.': '此 Conway 的模型、连接器和插件。账户级设置保留在您的 Claude 设置中。',
  'Pick based on what your tools actually do, not what your product can do. We cross-check this against your tools\' readOnlyHint / destructiveHint annotations — a mismatch will be flagged below and during review.': '根据工具的实际功能选择，而非产品的功能。我们将根据工具的 readOnlyHint/destructiveHint 注释进行交叉检查——不匹配将在下方和审核期间标记。',
  'How effectively users prompt, delegate, and verify': '用户提示、委托和验证的效率',
  'Show Logs in Finder': '在 Finder 中显示日志', 'Show Logs in Explorer': '在资源管理器中显示日志',
  'Show Logs in File Manager': '在文件管理器中显示日志',
  'Show Cowork Session Data in Finder': '在 Finder 中显示 Cowork 会话数据',
  'Show Cowork Session Data in Explorer': '在资源管理器中显示 Cowork 会话数据',
  'Show Cowork Session Data in File Manager': '在文件管理器中显示 Cowork 会话数据',
  'Select extension': '选择扩展', 'Select Extension Folder': '选择扩展文件夹',
  'Waiting for Claude...': '等待 Claude…', 'Claude is thinking...': 'Claude 正在思考…',
  'Stop generating': '停止生成', 'Continue generating': '继续生成',
  'Copied version to clipboard': '版本号已复制到剪贴板', 'Cache cleared successfully': '缓存已清理成功',
  'Allow Claude to cowork in {path}?': '允许 Claude 在 {path} 协作？',
  'Allow Claude to use {toolName}?': '允许 Claude 使用 {toolName}？',
  'This will open {appName} to compose a message to {email}.': '将打开 {appName} 撰写发送给 {email} 的消息。',
  'This will open your default email application to compose a message to {email}.': '将打开默认邮件应用撰写发送给 {email} 的消息。',
  'Open email link?': '打开邮件链接？',
  'Claude for macOS and Windows can connect Claude Cowork and Claude Code to maker devices over BLE, so developers can build hardware that displays permission prompts, recent messages, and other interactions.': 'Claude 桌面版可通过 BLE 将 Cowork 和 Code 连接到外部设备，让开发者构建可显示权限提示、最近消息的硬件。',
  'Scanning for 5s…': '正在扫描（5 秒）…',
  '{skipped, plural, one {# folder was} other {# folders were}} skipped because it overlaps a protected location or is the home/root directory.': '已跳过 {skipped} 个文件夹（与受保护位置或根目录重叠）。',
  'Your administrator has restricted which folders can be used here. {skipped, plural, one {# folder was} other {# folders were}} skipped.': '管理员限制了可用的文件夹，已跳过 {skipped} 个。',
  'This will delete and re-download your workspace. Your existing session data will be preserved.': '将删除并重新下载工作空间，现有会话数据将被保留。',
  'The extension could not be installed. Please ensure the extension folder is valid and try again. The error was: {errorMessage}': '无法安装扩展，请确保扩展文件夹有效后重试。{errorMessage}',
  'The extension could not be installed due to the following error: {errorMessage}': '无法安装扩展：{errorMessage}',
  'The extension could not be previewed due to the following error. Please ensure the DXT file is valid and try again. {errorMessage}': '扩展无法预览，请确保 DXT 文件有效后重试。{errorMessage}',
  'The extension {extensionName} {organizationText} has an update available.': '扩展 {extensionName} {organizationText} 有可用更新。',
  'This desktop extension will be installed on your computer and made available to Claude.': '此桌面扩展将安装在您的计算机上供 Claude 使用。',
  'This desktop extension will be installed on your computer. In order to install this extension we need to fetch a few dependencies. This may take a few minutes.': '此桌面扩展将安装在您的计算机上，需要获取一些依赖项，可能需要几分钟。',
  'Do you want to install {extensionName}?': '是否安装 {extensionName}？',
  'Would you like to submit your issue with debug logs?': '是否要提交附带调试日志的问题？',
  'Submit feedback and reinstall workspace': '提交反馈并重新安装工作空间',
  'Skip feedback and reinstall': '跳过反馈并重新安装',
  'The Chrome extension\'s session expired.': 'Chrome 扩展会话已过期。',
  'Make sure you are signed in to Claude in Chrome with the same account as Claude Desktop.': '请确保 Chrome 中登录 Claude 的账户与桌面版相同。',
  'Login to Claude in Chrome': '在 Chrome 中登录 Claude',
  'Sign back in to Claude in Chrome': '重新登录 Chrome 中的 Claude',
  'Install Claude in Chrome': '在 Chrome 中安装 Claude',
  'Install and restart Chrome': '安装并重启 Chrome',
  'Open Chrome': '打开 Chrome',
  'You\'ll need to grant Claude access to your microphone in System Settings.': '您需要在系统设置中授予 Claude 麦克风权限。',
  'You\'ve used {key} to speak to Claude, but Claude needs microphone permission.': '您已使用 {key} 与 Claude 通话，但需要麦克风权限。',
  'Claude needs microphone permission': 'Claude 需要麦克风权限',
  'Or, you can turn off Claude\'s dictation feature to avoid seeing this message when you press your hotkey.': '或关闭听写功能以避免按下快捷键时显示此消息。',
  'Claude\'s installation appears to be corrupted. Reinstall Claude from claude.com/download to use this feature.': 'Claude 安装已损坏，请从 claude.com/download 重新安装。',
  'Claude works best when run from your Applications folder.': 'Claude 从 Applications 文件夹运行效果最佳。',
  'Claude could not be moved to the Applications folder.': '无法将 Claude 移动到 Applications 文件夹。',
  'Claude will have read and write access to files in {path}.': 'Claude 将拥有 {path} 中文件的读写权限。',
  'Claude will have read and write access to this folder.': 'Claude 将拥有此文件夹的读写权限。',
  'This artifact wants to open a {protocol} link in another app: {url}': '此内容想在另一应用中打开 {protocol} 链接：{url}',
  'This artifact wants to open {appName} with the link {url}': '此内容想通过链接 {url} 打开 {appName}',
  'Always allow {protocol} links from artifacts': '始终允许来自内容的 {protocol} 链接',
  'Open link in another app?': '在另一应用中打开链接？',
  'We failed to open a link using your system\'s default application for this type of link.': '无法使用系统默认应用打开此类型链接。',
  'Link couldn\'t be opened': '无法打开链接',
  'Open this conversation in the Claude desktop app to finish setup.': '在 Claude 桌面应用中打开此对话以完成设置。',
  'The following entries in claude_desktop_config.json are not valid MCP server configurations and were skipped: {names}': 'claude_desktop_config.json 中的以下条目无效，已被跳过：{names}',
  'There was an error reading or parsing claude_desktop_config.json: {error}': '读取或解析 claude_desktop_config.json 出错：{error}',
  'There was an error reading or parsing developer_settings.json: {error}': '读取或解析 developer_settings.json 出错：{error}',
  'Your settings file was corrupted and has been reset to defaults.': '设置文件已损坏并已重置为默认值。',
  'This app\'s file ownership is preventing auto-updates from working smoothly.': '文件所有权阻止了自动更新的正常运行。',
  'The ownership fix didn\'t complete. Auto-updates may not work until this is resolved.': '所有权修复未完成，自动更新可能无法正常工作。',
  'That feature change requires an app restart to take effect.': '功能更改需要重启应用才能生效。',
  'Version {currentVersion} → {newVersion} Would you like to install this update?': '版本 {currentVersion} → {newVersion}，是否安装此更新？',
  'Restart to update to {updateVersion}': '重启以更新到 {updateVersion}',
  'A new version is available. It will be downloaded and installed automatically.': '新版本可用，将自动下载并安装。',
  'The application must be restarted for this change to take effect.': '必须重启应用才能生效。',
  'The application will now restart.': '应用即将重启。',
  'Error resetting application data': '重置应用数据出错',
  'Error cleaning up Cowork disk space': '清理 Cowork 磁盘空间出错', 'Error deleting VM sessions': '删除虚拟机会话出错',
  'Error deleting VM bundle': '删除虚拟机包出错',
  'Claude is working in {count, plural, one {# session} other {# sessions}}. Quitting now will interrupt that work.': 'Claude 正在 {count} 个会话中工作，退出将中断这些工作。',
  'Please quit the other copy of Claude and try again.': '请退出另一个 Claude 实例后重试。',
  'SEE6jniXQK': '请退出另一个 Claude 实例后重试。',
  'Claude is still working': 'Claude 仍在工作中',
  'Claude crashed repeatedly. Try restarting the app, or disable hardware acceleration in Settings.': 'Claude 反复崩溃，请重启应用或在设置中禁用硬件加速。',
  'Claude Code for Desktop has been disabled by your organization administrator': 'Claude Code 桌面版已被组织管理员禁用',
  'Claude Nest has been restricted from accessing the microphone by a system administrator': '系统管理员已限制 Claude 访问麦克风',
  'The following extensions have been disabled because they are not allowed in your current organization:': '以下扩展已被禁用（在当前组织中不被允许）：',
  'Access denied by your organization. Contact your administrator.': '已被组织拒绝访问，请联系管理员。',
  'Your administrator has disabled adding folders.': '管理员已禁用添加文件夹功能。',
  'The extension directory has been disabled on your computer.': '您的计算机上已禁用扩展目录。',
  'Enable the secureVmFeaturesEnabled preference to use this feature.': '请启用 secureVmFeaturesEnabled 偏好设置。',
  'Ask your IT administrator to enable the secureVmFeaturesEnabled setting in the Claude desktop configuration profile.': '请让 IT 管理员在 Claude 配置文件中启用 secureVmFeaturesEnabled。',
  'Cowork requires Windows 10 build 2004 or later.': 'Cowork 需要 Windows 10 2004 或更高版本。',
  'Cowork requires virtualization.': 'Cowork 需要虚拟化支持。',
  'Cowork requires macOS 14.0 (Sonoma) or later.': 'Cowork 需要 macOS 14.0（Sonoma）或更高版本。',
  'Cowork requires Claude Desktop be installed with our modern installer': 'Cowork 需要使用新版安装程序安装 Claude 桌面版。',
  'Cowork is not currently supported on {platform} with an {arch} CPU': 'Cowork 当前不支持 {platform} 上的 {arch} CPU',
  'Cowork is not currently supported on {platform}': 'Cowork 当前不支持 {platform}',
  'This version of Cowork doesn\'t support disk cleanup yet.': '此版本的 Cowork 尚不支持磁盘清理。',
  'Cowork isn\'t running, so there\'s nothing to clean up right now.': 'Cowork 未运行，当前无需清理。',
  'When <code>prompt</code> is present, your device can return a response:': '当提供 <code>prompt</code> 参数时，设备可返回响应：',
  'Advertise a name starting with <code>Claude</code> over the Nordic UART Service.': '通过 Nordic UART 服务广播以 <code>Claude</code> 开头的名称。',
  'The repository includes full details on building and connecting your own devices. Here\'s the short version.': '仓库包含完整的设备构建和连接说明，以下是简要版本。',
  'As an example, we built a desk pet that lives off permission approvals and interaction with Claude.': '例如，我们构建了一个靠权限审批维生的桌面宠物。',
  'The BLE API is only available when the desktop app is in developer mode.': 'BLE API 仅在桌面应用处于开发者模式时可用。',
  'This device requested an unencrypted connection.': '此设备请求了未加密连接。',
  'Freed {amount} of disk space.': '已释放 {amount} 磁盘空间。',
  'No space could be freed. Caches and temporary files are already clean.': '无法释放空间，缓存和临时文件已清理完毕。',
  'This removes caches and temporary files from Cowork sessions that aren\'t currently running.': '将清理未运行的 Cowork 会话的缓存和临时文件。',
  'That folder overlaps a protected location ({denied}) and can\'t be used here.': '该文件夹与受保护位置（{denied}）重叠，无法在此使用。',
  'Network (UNC) paths are not supported here.': '此处不支持网络（UNC）路径。',
  'Can\'t read folder, or it\'s empty or too large': '无法读取文件夹（为空或过大）',
  'Choose a folder inside: {roots}': '请在 {roots} 内选择文件夹：',
  'Allowed locations: {roots}': '允许的位置：{roots}',
  'Claude runs in the Notification Area': 'Claude 运行在通知区域',
  'Claude runs in the background even when you close the window. Click the Claude icon in the tray to reopen the app, or right-click to quit.': '关闭窗口后 Claude 仍在后台运行。点击系统托盘的 Claude 图标可重新打开，右键可退出。',
  'Your session has expired. Sign in again from the home screen.': '会话已过期，请从首页重新登录。',
  'Your session credentials expired.': '会话凭据已过期。',
  'Your session has expired.': '您的会话已过期。',
  'Your sign-in won\'t be saved on this device.': '登录信息不会保存到此设备。',
  'Your network redirected this request to {host}. Contact your IT administrator.': '网络将此请求重定向到 {host}，请联系 IT 管理员。',
  'The endpoint rejected the request. Check cert trust, IP allowlist, or auth headers.': '端点拒绝请求，请检查证书信任、IP 白名单或认证头。',
  'Connection is unencrypted': '连接未加密',
  'Connected · Encrypted': '已连接 · 已加密',
  'Extension {extensionId} is blocked by a security blocklist: {reason}': '扩展 {extensionId} 已被安全黑名单阻止：{reason}',
  'Don\'t Enable': '不要启用',
  'Don\'t ask again': '不再询问',
  'Allow': '允许', 'Deny': '拒绝', 'Allow access': '允许访问', 'Deny access': '拒绝访问',
  'Skip This Update': '跳过此更新',
  'Updates disabled by admin': '管理员已禁用更新',
  'Failed to check for updates: {error}': '检查更新失败：{error}',
  'Last update attempt failed...': '上次更新尝试失败…',
  'Checking for Updates...': '正在检查更新…',
  'Downloading Update...': '正在下载更新…',
  'Uploading…': '正在上传…',
  'Some sessions were skipped because they are currently running.': '部分会话被跳过（正在运行中）。',
  'Some items could not be removed.': '部分项目无法移除。',
  'No space was freed.': '未释放任何空间。',
  'Cowork Disk Cleanup': 'Cowork 磁盘清理',
  'Free Up Cowork Disk Space…': '释放 Cowork 磁盘空间…',
  'Delete Cowork VM Sessions and Restart…': '删除 Cowork 虚拟机会话并重启…',
  'Delete Cowork VM Bundle and Restart…': '删除 Cowork 虚拟机包并重启…',
  'Delete VM Sessions and Restart': '删除虚拟机会话并重启',
  'Delete VM Bundle and Restart': '删除虚拟机包并重启',
  'Delete and Restart': '删除并重启',
  'This will stop any running VM sessions, delete all local agent mode session data, and restart the app. This action cannot be undone. Are you sure you want to continue?': '此操作将停止所有运行中的虚拟机会话、删除所有本地代理模式会话数据并重启，不可撤销，确定继续？',
  'This will stop any running VM sessions, delete the VM bundle files, and restart the app. The bundle will be re-downloaded the next time you use the VM. Are you sure you want to continue?': '此操作将停止运行中的虚拟机会话、删除虚拟机包文件并重启，下次使用 VM 时将重新下载，确定继续？',
  'This will delete all application data including settings, cache, and login information. The application will restart after the reset. Are you sure you want to continue?': '此操作将删除所有应用数据（设置、缓存、登录信息），应用将重启，确定继续？',
  'Set up computer use': '设置计算机控制',
  'Enable Cowork VM Debug Logging': '启用 Cowork 虚拟机调试日志',
  'Enable Cowork SDK Debugging': '启用 Cowork SDK 调试',
  'Record Net Log (30s)': '录制网络日志（30 秒）',
  'View Process Logs': '查看进程日志',
  'Open MCP Log File': '打开 MCP 日志文件',
  'Open MCP Log File...': '打开 MCP 日志文件…',
  'Reload MCP Configuration': '重新加载 MCP 配置',
  'MCP Configuration Reload Failed': 'MCP 配置重载失败',
  'Failed to reload MCP configuration. Please check the logs for more details.': 'MCP 配置重载失败，请查看日志获取详情。',
  'Some MCP servers could not be loaded': '部分 MCP 服务器无法加载',
  'Configure Third-Party Inference…': '配置第三方推理…',
  'Load Remote Claude.ai': '加载远程 Claude.ai',
  'Load Local Claude.ai': '加载本地 Claude.ai',
  'Load Staging Claude.ai': '加载 Staging Claude.ai',
  'Fix ownership': '修复所有权',
  'Ownership fix failed': '所有权修复失败',
  'Fix required for auto-updates': '需要修复才能自动更新',
  'Select extension': '选择扩展',
  'Select Extension Folder': '选择扩展文件夹',
  'Open Extensions Folder...': '打开扩展文件夹…',
  'Open App Config File...': '打开应用配置文件…',
  'Open Developer Config File...': '打开开发者配置文件…',
  'Extension Installation Failed': '扩展安装失败',
  'Extension Preview Failed': '扩展预览失败',
  'Failed to install extension': '扩展安装失败',
  'Failed to preview extension': '扩展预览失败',
  'Failed to preview extension.': '扩展预览失败。',
  'This extension requires a valid signature': '此扩展需要有效签名',
  'No manifest.json found in extension file': '扩展文件中未找到 manifest.json',
  'No manifest.json found': '未找到 manifest.json',
  'Skill file error': '技能文件错误',
  'Skill file not found': '未找到技能文件',
  'Skill file too large': '技能文件过大',
  'The skill file could not be found.': '找不到技能文件。',
  'Skill file is too large. Maximum size is 30 MB.': '技能文件过大，最大为 30 MB。',
  'Failed to open skill file.': '无法打开技能文件。',
  'Claude is not ready to handle skill files. Try again after the app has fully loaded.': 'Claude 尚未就绪，请在应用完全加载后重试。',
  'Cannot open skill': '无法打开技能',
  'Organization Extension Update Available': '组织扩展更新可用',
  'Prototypes': '原型',
};

// ─── 翻译函数（合并模式：保留已有翻译）───
function translateFile(srcPath, existingPath, outName) {
  const en = JSON.parse(fs.readFileSync(srcPath, 'utf-8'));
  // Load existing zh-CN if available to preserve its translations
  let existing = {};
  try { existing = JSON.parse(fs.readFileSync(existingPath, 'utf-8')); } catch(e) {}
  const zh = {};
  let translated = 0, kept = 0, fromExisting = 0;
  for (const [key, val] of Object.entries(en)) {
    // Priority: existing translation (if it differs from EN) > our table > keep EN
    if (existing[key] !== undefined && existing[key] !== val) {
      zh[key] = existing[key];
      fromExisting++;
    } else if (T[val] !== undefined) {
      zh[key] = T[val];
      translated++;
    } else {
      zh[key] = val;
      kept++;
    }
  }
  const outFile = path.join(outDir, outName);
  fs.writeFileSync(outFile, JSON.stringify(zh, null, 2), 'utf-8');
  return { file: outFile, total: Object.keys(en).length, translated, fromExisting, kept };
}

// ─── 执行 ───
const d = claudeDir;
const results = {
  'zh-CN.json': translateFile(
    path.join(d, 'en-US.json'),
    path.join(d, 'zh-CN.json'),
    'zh-CN.json'
  ),
  'ion-i18n/zh-CN.json': translateFile(
    path.join(d, 'ion-dist', 'i18n', 'en-US.json'),
    path.join(d, 'ion-dist', 'i18n', 'zh-CN.json'),
    'i18n_zh-CN.json'
  ),
  'dynamic/zh-CN.json': translateFile(
    path.join(d, 'ion-dist', 'i18n', 'dynamic', 'en-US.json'),
    path.join(d, 'ion-dist', 'i18n', 'dynamic', 'zh-CN.json'),
    'dynamic_zh-CN.json'
  ),
};

// Print results as JSON and also a readable summary
console.log(JSON.stringify(results, null, 2));
console.log('\n---');
console.log('Output directory: ' + outDir);
